### PR TITLE
Compiling core as library and audio connectors as plugins.

### PR DESCRIPTION
**Pull request by ibancg**
This tackles issue #17

### CODE REVIEW

**Comment by ibancg** [comment]
@jairochapela please take a look. I will try to get Nicolas involved before merging this into `master`, for what it implies on the Debian side (splitting the project into several libraries).

**Comment by jairochapela** [comment]
It's a very promising enhancement.
How can we test it in deep?

**Comment by ibancg** [comment]
I guess by testing it on many platforms. So far I am confident it will run on Debian (`make install` does, so I hope the multipackage approach will too)

Maybe the best strategy will be to add an option in the `configure` script to enable/disable this, say `--enable-plugins`, so people can still go the old way for a while.

**Comment by ibancg** [comment]
After discussing with our Debian maintainer, we decided to only split between application/GUI and core library (with compile time dependencies to all audio systems). We therefore close this pull request and move to pull request #22.

**Pull request closed without merging**
