### PR TITLE
Adds a French menu item comment

### PR DESCRIPTION
**Pull request by trebmuh**
(as discussed by email)

### CODE REVIEW

**Comment by trebmuh** [comment]
Thanks for your quickness :+1:

**Comment by ibancg** [comment]
Thanks to you, let's see if we can bring this thing back to life.
Any feedback over features since 0.9.1 is welcome too.

**Comment by trebmuh** [comment]
Nice. If I think about something, I'll let you know.

**Comment by trebmuh** [comment]
@ibancg : I just saw that there is 2 bugs in the Debian BTS (bug tracker system). Patches are attached to those bugs. Please find those here : https://bugs.debian.org/cgi-bin/pkgreport.cgi?include=tags%3Apatch&exclude=tags%3Apending&pend-exc=done&repeatmerged=no&src=lingot
Hope that helps.

PS : for the one about adding a GenericName, you can add : "GenericName[fr]=Accordeur d'instrument de musique" to get its translation working in a French language environment.

**Comment by trebmuh** [comment]
There is another patch (already applied in the current debian package) : https://sources.debian.net/src/lingot/0.9.1-2/debian/patches/0001-Fixed-bug-643435-in-debian-error-format-not-a-string.patch/

**Pull request merged**
